### PR TITLE
Fix OGS byoyomi bug by having it own its timer

### LINKED ISSUE #156: OGS - timer doesn't update remaining byo-yomis
It frequently happens in OGS games, that, the byo-yomi counter for my opponent doesn't update, when a byo-yomi period is used. I thought the app just froze or something, because nothing was happening, but it's actually just a bug.

Actual experience/steps to reproduce:
- opponent's counter in the game is at YxZZ (Y being the number of byo-yomis remaining)
- counts down the first ZZ seconds
- when it reaches zero, it stays at Yx00 if my opponent hasn't played a move yet, and is using another byo-yomi period

Expected experience:
- when it reaches zero, it should say Y-1xZZ if my opponent hasn't played a move yet, and then count down from there

Opening the game on OGS, the timer is still counting down properly on the site for the opponent.

I haven't paid attention when it updates again, but it does in one of the following cases:
- they make a move, so the timer resets to the correct YxZZ
- I make a move and it's their turn again, and the their timer reset to the correct remaining byo-yomis left

I'll pay attention next time, and update the ticket with the correct timing of when it does update.

### PR DESCRIPTION
**Pull request by benjaminpjones**
Fixes #156, Alternative to #158 

This PR introduces GameTimer.  It is to fix the issue where main time didn't transition to period time in the OGS client.  I tried to write it so that it can be easily re-used for Tygem client or local gameplay.

## Follow-ups

Ultimately, I think we should extract the timer from `TimeDisplay` completely, deprecating the `localTimeControl` flag.

### CODE REVIEW

File: lib/audio/audio_controller.dart [hunk 1]
```diff
@@ -111,6 +111,12 @@ class AudioController {
       await _soloud.play(_enVoice.startToPlay, volume: voiceVolume);
   Future<void> pass() async =>
       await _soloud.play(_enVoice.pass, volume: voiceVolume);
-  Future<void> count(int i) async =>
-      await _soloud.play(_enVoice.count[i - 1], volume: voiceVolume);
+  Future<void> count(int i) async {
```
Comment (benjaminpjones) [inline lib/audio/audio_controller.dart]: these changes caused TimeDisplay to send in `0`.  Should probably fix that interaction, but also good to fail gracefully rather than crashing.

File: lib/game_client/ogs/ogs_game.dart [hunk 2]
```diff
@@ -433,18 +453,41 @@ class OGSGame extends Game {
   void _handleClock(Map<String, dynamic> data) {
     _logger.fine('Received clock update for game $id');
 
+    // If the game has already ended, stop both timers and ignore clock updates
```
Comment (benjaminpjones) [inline lib/game_client/ogs/ogs_game.dart]: OGS sends one clock message after the game.  No idea what that's about.

File: lib/game_client/ogs/ogs_game.dart [hunk 3]
```diff
@@ -433,18 +453,41 @@ class OGSGame extends Game {
...
+        } else {
+          _blackTimer.stop();
+          blackTime.value = (blackTime.value.$1 + 1, newState);
+        }
       }
 
       if (whiteTimeData != null) {
-        whiteTime.value =
-            (whiteTime.value.$1 + 1, _parseOGSTimeData(whiteTimeData));
+        final newState = _parseOGSTimeData(whiteTimeData);
```
Comment (ale64bit) [inline lib/game_client/ogs/ogs_game.dart]: a bit of duping here, maybe we should refactor it into its own function? (it can take the timer and the listener as arguments)

File: lib/game_client/game_timer.dart [hunk 4]
```diff
@@ -0,0 +1,120 @@
...
+
+  GameTimer({
+    required TimeState initialState,
+  })  : _baseState = initialState,
+        _notifier = ValueNotifier((0, initialState));
+
+  /// The current time state and a tick counter.
+  /// The tick counter increments each time the state changes, allowing listeners
+  /// to detect updates even when the TimeState values might be identical.
+  ValueNotifier<(int, TimeState)> get timeNotifier => _notifier;
```
[the remark this answers is not in the document]
Comment (benjaminpjones) [reply lib/game_client/game_timer.dart]: Sounds good, `GameTimer` now extends `ValueNotifier`

File: lib/game_client/ogs/ogs_game.dart (hunk 3 above)
Comment (benjaminpjones) [reply lib/game_client/ogs/ogs_game.dart]: SGTM.  The code isn't much shorter, but I agree the de-duped logic is better for maintenance.

File: lib/game_client/game_timer.dart [hunk 5]
```diff
@@ -0,0 +1,120 @@
...
+  ///
+  /// If the timer is already running, it will be stopped first.
+  /// The new state becomes the base state and the timer starts counting down.
+  void start(TimeState newState) {
+    stop();
+    _baseState = newState;
+    _startTime = clock.now();
+    _notifier.value = (_notifier.value.$1 + 1, newState);
+
+    _timer = Timer.periodic(const Duration(seconds: 1), (_) {
```
[the remark this answers is not in the document]
Comment (ale64bit) [reply lib/game_client/game_timer.dart]: that's right! Apologies for the noise :pray: not sure why I thought it could be paused/resumed.

**Review by ale64bit — APPROVED** [review]
